- scenes/networkWowNetwork.py
first try on a scraper
dirty hack on trailer and external_id (i have absolute no clue of regex)
> WowNetwork

- scenes/networkBang.py
- scenes/networkOnePassForAllSites.py
- scenes/networkProjectOneService.py
- scenes/networkSpizoo.py
- scenes/networkTeamSkeet.py
- scenes/siteLetsDoeIt.py
Addding:
"1 Pass For All Sites" network
"Spizoo" network
Added several sites to Mindgeek (and sorted them).  Added a few to TeamSkeet, and tweaked the Bang! scraper.  (It was calculating on too many JSON result entries and missing Bang! Originals due to capitalization.  Also it would fail on entries with no DVD IDs, so now it will fail with a console notice.  It will pull 50,000 entries now before bailing out, which I imagine is a limitation of the site)
> Adding more sites

- scenes/siteHushpass.py
- scenes/siteHussiepass.py
Adding Hushpass site and Hussiepass sites (Hussiepass, POV Pornstars and See Him Fuck)
> initial commit

- performers/FemdomEmpirePerformer.py
- performers/LegalPornoPerformer.py
- performers/networkPuffyPerformer.py
- performers/sitePerfectGonzoPerformer.py
- scenes/FemdomEmpire.py
- scenes/siteOnly3X.py
- scenes/sitePefectGonzo.py
Fixing "/?nats" in id, adding Sapphix site (not under PG umbrella), getting rid of duplicate tags
> tweaks to Perfect Gonzo sites

- scenes/moviesAdultDVDEmpire.py
- scenes/networkTeamSkeet.py
- scenes/siteWatch4Beauty.py
Fixing tags and scene urls, though premium site urls aren't fixed yet
> tweaking primary TeamSkeet site

- scenes/networkVixen.py
Only one problem unsolved, site have cloudflare protection
~~and not all scenes scraped, because of `per_page`~~
> Update Vixen API to GraphQL

- performers/networkTopWebModelsPerformer.py
- performers/siteBabeArchivePerformer.py
- performers/siteExposedWhoresPerformer.py
- performers/sitePhilavisePerformer.py
- scenes/NewSensations.py
- scenes/networkAndomark.py
- scenes/networkPornPros.py
- scenes/networkTopWebModels.py
- scenes/networkVna.py
- scenes/siteBabeArchives.py
- scenes/siteExposedWhores.py
- scenes/siteFamilyTherapyXXX.py
- scenes/sitePhilavise.py
You might want to take a look at this.  The image seems to be dynamically created based off the trailer, but you might see a way to pull the image
> initial commit of FamilyTherapyXXX

- scenes/networkTopWebModels.py
- scenes/siteHotGuysFuck.py
- scenes/siteHotMilfsFuck.py
Already had this in I believe, but must have overwritten the file with HotMilfsFuck
> Committing HotGuysFuck

- scenes/networkBang.py
- scenes/networkGammaEnterprises.py
- scenes/networkNubiles.py
- scenes/networkProjectOneService.py
- scenes/siteChastityBabes.py
- scenes/siteEvolvedFights.py
- scenes/siteSexMex.py
Nothing of real note, some various tweaks, and putting in all of the ProjectOne sites retrieved so it's easy to grep for existence.
> various tweaks to sites

- scenes/networkAdulttimeAPI.py
- scenes/networkGammaEnterprises.py
- scenes/networkNomadMedia.py
- scenes/networkNubiles.py
- scenes/networkPuffy.py
- scenes/siteChastityBabes.py
This ONLY pulls sites that are a part of AdultTime and have a publicly accessible video index page.  No scenes that are hidden or require login will be scraped
> initial commit of AdultTime public api scraper

- scenes/networkPorncz.py
Required [#12](https://github.com/ThePornDatabase/scrapy/pull/12)
> Add usage date_formats and minor changes

- scenes/networkData18.py
- scenes/networkScorePass.py
- scenes/siteCumLouder.py
Only useful for adding sites that no longer exist.  Can't really use with existing sites since the external ids won't match, and can't guarantee names even do (though they usually do).
Just a one-time use for each site
> Initial commit of Data18

- performers/siteCumPerfectionPerformer.py
- performers/siteHookupHotshotPerformer.py
- scenes/networkPorncz.py
- scenes/siteCumPerfection.py
- scenes/siteHookupHotshot.py
> Initial commit of Hookup Hotshot scenes/performers

- performers/networkAllJapanesePassPerformer.py
- performers/site5DollahPerformer.py
- scenes/networkAllJapanesePass.py
- scenes/networkTopWebModels.py
- scenes/site5Dollah.py
- scenes/siteSecretFriends.py
and tweak for SecretFriends dates
> initial commit of 5Dollah

- performers/networkVRLifePerformer.py
- scenes/networkVRLife.py
Relatively straightforward scraper for VRLife sites. It does throw an Exception when new Bio information is available that has not been mapped to TPD's performer item definition. Easy to remove. Models could be scraped in one go, the post_data allows for limits above the default (15), not sure what is preferred, so I kept it inline with how the website works.
First time doing this, so let me know if I need to change anything. I'm not on Discord.
> Implemented VRLife Scraper

- scenes/networkPOVR.py
Added POST request before start_request to update session
> Updated POVR to include all content

- scenes/siteVirtualTaboo.py
Added duration parsing, changed network to Virtual Taboo. Removed inlined check_item function
> Add duration to Virtual Taboo and changed network

- performers/site18YogaPerformer.py
- scenes/site18Yoga.py
Based on @Gykes's design. Added duration and performer parser.
> 18yoga spider scene + performer

- scenes/networkAdultEmpireCash.py
- Fixed error in start_urls.
- Updated JaysPOV & Bruthas Inc scene XPath
> Fixed JaysPOV & Bruthas Inc

- scenes/sitePrivate.py
> Update sitePrivate.py tags
